app_lego/старое/admin_panel/forms.py
from flask import flash
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField, BooleanField
from wtforms.validators import DataRequired, EqualTo, Length, Email, ValidationError


class LoginForm(FlaskForm):
    email = StringField('Емейл', validators=[DataRequired(), Email()])
    password = PasswordField('Пароль', validators=[DataRequired()])
    remember = BooleanField('Запомнить меня')
    submit = SubmitField('Войти')

app_lego/старое/admin_panel/routes.py
from flask import render_template, redirect, url_for, request, flash, Request, Blueprint
from flask_login import current_user, login_user, logout_user, login_required
from app_lego.models import check_password_hash
from app_lego.models import User
from app_lego.admin_panel.forms import LoginForm
from app_lego import db
from datetime import datetime
from app_lego.models import Part, Category, User



admin_panel = Blueprint('admin_panel', __name__)

@admin_panel.route('/admin_panel')
def index():
    return render_template('admin_panel/spisok_zakazov.html', title='Панель администратора')
        


@admin_panel.route('/admin_panel/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('admin_panel.index'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            flash(f'Вы вошли в аккаунт пользователя {user.username}', 'info')
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('admin_panel.index'))
        else:
            flash('Войти не удалось. Пожалуйста, проверьте электронную почту или пароль.', 'danger')
    return render_template('admin_panel/login.html', form=form, title='Авторизация', legend='Войти')


@admin_panel.route('/admin_panel/account', methods=['GET', 'POST'])
@login_required
def account():
    return render_template('admin_panel/account.html', title='Аккаунт', current_user=current_user)


@admin_panel.route('/admin_panel/logout')
def logout():
    current_user.last_seen = datetime.now()
    db.session.commit()
    logout_user()
    return redirect(url_for('admin_panel.index'))



@admin_panel.route('/admin_panel/spisok_zakazov')
def zakaz():
    
    return render_template('admin_panel/spisok_zakazov.html', title = 'Ваша корзина')


@admin_panel.route('/admin_panel/catalog', methods=['GET'])
def catalog():
    search = request.args.get('search')
    page = request.args.get('page')
    if page and page.isdigit():
        page = int(page)
    else:
        page = 1
    if search:
        parts = Part.query.filter(Part.description.contains(search) | Part.color.contains(search))
    else:
        parts = Part.query.order_by(Part.price)
    pages = parts.paginate(page = page, per_page = 30)
    return render_template('admin_panel/catalog.html', title='Каталог', pages = pages)


@admin_panel.route('/admin_panel/create', methods=['POST', 'GET'])
def create():
    if request.method == 'POST':
        lot_id = request.form['lot_id']
        price = request.form['price']
        color = request.form['color']
        description = request.form['description']
        quantity = request.form['quantity']
        category_id = request.form['category_id']
        remarks = request.form['remarks']
        
        # Преобразование цены в число
        try:
            price_value = float(price)
        except ValueError:
            return "Некорректная цена", 400

        item = Part(lot_id = lot_id, price=price_value, color=color, description=description, quantity=quantity, category=category_id, remarks=remarks)
        
        try:
            db.session.add(item)
            db.session.commit()
            return redirect('/admin_panel')
        except Exception as e:
            # Можно залогировать ошибку
            print(f"Ошибка при добавлении объекта: {e}")
            return 'Произошла ошибка при сохранении объекта!'
    else:
        return render_template('admin_panel/create.html', title='Создание объекта')
    

app_lego/старое/user/routes.py
from flask import render_template, redirect, url_for, request, flash, Request, Blueprint
from flask_login import current_user, login_user, logout_user, login_required
from app_lego.models import check_password_hash
from app_lego.models import User
from app_lego.user.forms import RegistarionForm
from app_lego import bcrypt, db


users = Blueprint('users', __name__)


@users.route('/register', methods=['GET', 'POST'])
def register():
    form = RegistarionForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(username=form.username.data, email=form.email.data, password = hashed_password)
        db.session.add(user)
        db.session.commit()
        
        # full_path = os.path.join(os, getcwd(), 'app_lego/static', 'profile_pics', user.username)
        # if not os.path.exists(full_path):
        #     os.mkdir(full_path)
        # shutil.copy(f'{os.getcwd()}/app_lego/static/profile_pics/default.jpg', full_path)
        flash(' Ваш аккаунт был создан. Вы можете войти.', 'success')
        
        return redirect(url_for('main.login'))
    return render_template('registration.html', form = form, title = 'Регистрация', legend='Регистрация')

# @main.route('/condition')
# def condition():
#     return render_template('condition.html', title = 'Условия покупки')
        


# @main.route('/login', methods=['GET', 'POST'])
# def login():
#     if current_user.is_authenticated:
#         return redirect(url_for('main.index'))    
#     form = LoginForm()
#     if form.validate_on_submit():
#         user = User.query.filter_by(email=form.email.data).first()
#         if user and check_password_hash(user.password, form.password.data):
#             login_user(user, remember=form.remember.data)
#             next_page = request.args.get('next')
#             return redirect(next_page) if next_page else redirect(url_for('main.account'))
#         else:
#             flash('Войти не удалось. Пожалуйстаб проверьте электронную почту или пароль.', 'danger')
#     return render_template('login.html', form=form, title='Авторизация', legend='Войти')


# @main.route('/account', methods=['GET', 'POST'])
# @login_required
# def account():
#     return render_template('account.html', title='Аккаунт', current_user=current_user)


# @main.route('/logout')
# @login_required
# def logout():
#     logout_user()
#     return redirect(url_for('main.index'))

# @main.route('/details')
# def details():
#     return render_template('details.html', title = 'Каталог')

app_lego/старое/templates/admin_panel/account.html
{% extends "admin_panel/layout.html" %}


{% block content %}
<h1> Аккаунт пользователя {{current_user.username}}</h1>

{% if current_user.is_authenticated %}

<p> {{ current_user.username }}</p>
<p> {{ current_user.email }}</p>

{% endif %}

{% endblock content %}

app_lego/старое/templates/admin_panel/catalog.html
{% extends "admin_panel/layout.html" %}

{% block content %}




    <body class="bg-gray-100 flex items-center justify-center min-h-screen">
        <div class="col-md-9">
        <div class="d-flex justify-content-between align-items-center">
            <h4>Каталог деталей</h4>
        </div>

        <table class="table table-striped product-table">
            <thead>
                <tr>
                    <th scope="col">Изображение</th>
                    <th scope="col">Состояние</th>
                    <th scope="col">Цвет</th>
                    <th scope="col">Описание</th>
                    <th scope="col">Информация</th>
                </tr>
            </thead>
            <tbody>

                {% for el in pages.items %}
                    <tr>
                        <td><img src="https://via.placeholder.com/50x50/0000FF/ffffff?text=Blue" alt="Изображение"></td>
                        <td>{{el.isNew}}</td>
                        <td>{{el.color}}</td>
                        <td>{{el.description}}</td>
                        <td>
                            <span>Наличие: {{el.quantity}}</span><br>
                            <span>Цена: {{el.price}} росс.рублей</span><br>
                        </td>
                    </tr>
                {% endfor%}

                
            </tbody>
            
        </table>
        <nav>
            <ul class="pagination justify-content-center">
                <li class="page-item {% if not pages.has_prev %}disabled{% endif %}">
                    <a class="page-link" href="{{ url_for('main.index', page=pages.prev_num) }}">Предыдущая</a>
                </li>
                {% for p in pages.iter_pages(left_edge=2, right_edge=2, left_current=2, right_current=2) %}
                    {% if p %}
                        <li class="page-item {% if p == pages.page %}active{% endif %}">
                            <a class="page-link" href="{{ url_for('main.index', page=p) }}">{{ p }}</a>
                        </li>
                    {% else %}
                        <li class="page-item disabled"><span class="page-link">...</span></li>
                    {% endif %}
                {% endfor %}
                <li class="page-item {% if not pages.has_next %}disabled{% endif %}">
                    <a class="page-link" href="{{ url_for('main.index', page=pages.next_num) }}">Следующая</a>
                </li>
            </ul>
        </nav>
        
    
    </div>
        <button class="btn btn-danger"><a href="/zakaz">Перейти в корзину</a></button>
    </div>
    </div>
    </body>


    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"></script>

  
    

{% endblock content %}

app_lego/старое/templates/admin_panel/create.html
{% extends "admin_panel/layout.html" %}

{% block title %}
    <title> Добавление новой записи с базу данных</title>
{% endblock title %}

{% block content %}

<div class='container'>

    <div class="bg-white p-8 rounded-xl shadow-md w-full max-w-md">
        <div class="flex flex-col items-center mb-6">
        <h1 class="text-2xl font-bold text-gray-800">Добро пожаловать на страницу добавления нового товара!</h1>
        <p class="text-gray-500 text-sm mt-1">Для добавления товара, пожалуйста, заполните поля.</p>
        </div>
    
        <form class="space-y-4" method='post'>
        <div>
            <label for="lot_id" class="block text-sm font-medium text-gray-700"> ID детали</label>
            <input name='lot_id' type="text" id="lot_id" class="mt-1 w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:outline-none">
        </div>
        <div>
            <label for="price" class="block text-sm font-medium text-gray-700">Цена</label>
            <input name='price' type="number" id="price" class="mt-1 w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:outline-none">
        </div>

        <div>
            <label for="color" class="block text-sm font-medium text-gray-700">Цвет </label>
            <input name='color' type="text" id="color" class="mt-1 w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:outline-none">
        </div>
        <div>
            <label for="description" class="block text-sm font-medium text-gray-700">Описание</label>
            <input name='description' type="text" id="description" class="mt-1 w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:outline-none">
        </div>

        <div>
            <label for="quantity" class="block text-sm font-medium text-gray-700">Количество</label>
            <input name='quantity' type="number" id="quantity" class="mt-1 w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:outline-none">
        </div>

        <div>
            <label for="category_id" class="block text-sm font-medium text-gray-700">Категория</label>
            <input name='category_id' type="text" id="category_id" class="mt-1 w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:outline-none">
        </div>

        
        <div>
            <label for="remarks" class="block text-sm font-medium text-gray-700">Заметки</label>
            <input name='remarks' type="text" id="remarks" class="mt-1 w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:outline-none">
        </div>
    
        
    
        <button type="submit" class="w-full bg-blue-600 text-white py-2 rounded-lg hover:bg-blue-700 transition duration-300">
            Добавить товар
        </button>
        </form>
    

    </div>
</div>

    {% endblock content %}

app_lego/старое/templates/admin_panel/layout.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel = 'stylesheet' href = "{{url_for('static', filename= 'css/style.css')}}">
    
    {% block title %}
      <title> {{ title if title else 'BrickIt' }} </title>
    {% endblock title %}




    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet">
    <style>
        .header {
            background-color: #f8f9fa;
            padding: 20px;
        }
        .sidebar {
            background-color: #f8f9fa;
            padding: 10px;
        }
        .product-table img {
            width: 50px;
            height: 50px;
            object-fit: cover;
        }
    </style>
</head>
<body>



    {% block menu %}

      <header class = 'header'> 
        <div class = 'logo'>
          <img src=' {{ url_for('static', filename='img/logo.png') }}' alt='logo'>
          <nav class="navbar navbar-expand-lg navbar-light">
            <a class="navbar-brand" href="{{url_for('main.index')}}">BrickIt</a>
          </nav>
          <ul class = 'main_menu'>

    

            <li><a href = '#'> <p>Загрузить Wanted list c bl </p></a></li>
            <li><a href = '{{url_for('admin_panel.create')}}'> <p>Создание объекта </p></a></li>
            <li><a href = '{{url_for('admin_panel.catalog')}}'> <p>Каталог </p></a></li>
            <li><a href = '{{url_for('admin_panel.zakaz')}}'> <p>Просмотр заказов </p></a></li>
            <li><a href = '{{url_for('admin_panel.index')}}'> <p>Выход </p></a></li>

            
            <li><a href = '{{url_for('admin_panel.login')}}'> <p> Логин </p></a></li>
            




          </ul>
        </div>

      </header>
    {% endblock menu %}  



    

            

 


<div class = 'wrap'>

  <div class="container-fluid">
    <div class="row">
        <!-- Sidebar -->
      

      <div class='col-md-9 content'>

        <div class='empty_block'></div>
        <main role='main' class='#'>

            <div class = 'col_md_12'>
              {% with messages = get_flashed_messages(with_categories=True) %}
                {% if messages %}
                  {% for category, message in messages %}
                    <div class='alert alert-{{ category }}'>{{ message }}</div>
                  {% endfor %}
                {% endif %}
              {% endwith %}



              {% block content %}{% endblock content %}
            </div>
          </div>
        </main>
      </div>
    </div>
  </div>


    {% block details %} {% endblock details %}




  {% block main_page %}

  {% endblock main_page %}



  



  {% block footer %}

  <footer class='footer'>
    <p>&copy; 2025 </p>
  </footer>
  {% endblock footer %}



</div>
</body>
</html>

app_lego/старое/templates/admin_panel/login.html
{% extends "admin_panel/layout.html" %}
{% block main_page %}
{% endblock main_page %}

{% block content %}

<div class='login_form'>
    <form action='' method='POST'>
        {{ form.hidden_tag() }}
        <legend class='legend'>{{ legend }}</legend>
        
        <div class='form-group'>
            {% if form.email.errors %}
                {{ form.email(class='is-invalid', placeholder='Емайл') }}
                <div class='invalid-feedback'>
                    {% for error in form.email.errors %}
                        <span>{{ error }}</span>
                    {% endfor %}
                </div>
            {% else %}
                {{ form.email(class='form-post-title', placeholder='Емайл') }}
            {% endif %}
        </div>

        <div class='form-group'>
            {% if form.password.errors %}
                {{ form.password(class='form-post-title is-invalid', placeholder='Пароль') }}
                <div class='invalid-feedback'>
                    {% for error in form.password.errors %}
                        <span>{{ error }}</span>
                    {% endfor %}
                </div>
            {% else %}
                {{ form.password(class='form-post-title', placeholder='Пароль') }}
            {% endif %}
        </div>

        <div class='form-check'>
            {{ form.remember(class='form-check-input') }}
            {{ form.remember.label(class='form-check-label') }}
        </div>

        <div class='form-group'>
            {{ form.submit(class='btn_sign_in') }}
        </div>
    </form>
</div>

{% endblock content %}

app_lego/старое/templates/admin_panel/registration.html
{% extends "admin_panel/layout.html" %}


{% block content %}


<div class='login_form'>
    <form action='' method='POST'>
        {{form.hidden_tag()}}
        <legend class='legend'>{{  legend }}</legend>
        <div class='form-group'>
            {% if form.email.errors %}
                {{ form.email(class='is-invalid', placeholder='Емайл')}}
                <div class='invalid-feedback'>
                    {% for errors in form.email.errors %}
                    <span>{{error}}</span>
                    {% endfor %}
                </div>
                {% else %}
                    {{ form.email(class='form-post-title', placeholder='Емайл')}}
                {% endif %}
        </div>

            {% if form.password.errors %}
                {{ form.password(class='form-post-title is-invalid', placeholder='Пароль')}}
                <div class='invalid-feedback'>
                    {% for errors in form.password.errors %}
                    <span>{{error}}</span>
                    {% endfor %}
                </div>
                {% else %}
                    {{ form.password(class='form-post-title', placeholder='Пароль')}}
                {% endif %}

            {% if form.confirm_password.errors %}
            {{ form.confirm_password(class='form-post-title is-invalid', placeholder='Подтвердите пароль')}}
            <div class='invalid-feedback'>
                {% for errors in form.confirm_password.errors %}
                <span>{{error}}</span>
                {% endfor %}
            </div>
            {% else %}
                {{ form.confirm_password(class='form-post-title', placeholder='Подтвердите пароль')}}
            {% endif %}
   

            <div class='form-group'>
                {{form.submit(class='btn_sign_in')}}
            </div>



    </form>



    <div class='border-top'>
        <small class='text-nuted'> Уже есть аккаунт? <a class='ml-2' href='{{ url_for('users.login')}}'>Войти</a></small>
    </div>

</div>

{% endblock content %}

app_lego/старое/templates/admin_panel/spisok_zakazov.html
{% extends "admin_panel/layout.html" %}


{% block content %}


{% if current_user.is_authenticated %}

<h1> Список заказов</h1>

{% else %}

<h1> Войдите в систему администратора </h1>

{% endif %}

{% endblock content %}